# Generated by Django 3.1.7 on 2021-05-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.CharField(default='False', max_length=32)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_activities', to='meet.activity')),
            ],
        ),
    ]
