# Generated by Django 3.1.7 on 2021-05-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0008_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleted',
            name='deleted',
        ),
    ]
